### ISSUE TITLE
Duplicated Schema and Definition Ids

### ISSUE THREAD

**Issue by yunxi-zhang** [hyperledger/aries-cloudagent-python#1786]
**Context:**

- ACA-Py version: 0.7.3
- Docker image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.3
- Askar: flag on
- Postgres: flag on
- Indy: Soverin BuildNet

**Issue**
After an issuer creates a new schema and definition, when querying the schema and definition ids, response payload shows duplicated ids.

- API to query schemas: /schemas/created

<img width="631" alt="image" src="https://user-images.githubusercontent.com/16185797/170987155-a5520ebd-26cd-4bd3-97ad-d066ab0fb3d1.png">

- API to query definitions: /credential-definitions/created

<img width="640" alt="image" src="https://user-images.githubusercontent.com/16185797/170987209-5837d65d-fef7-49bd-981d-15201bf7d8ed.png">

**Expected Result**
Shouldn't show duplicated data in each response payload.

**Comment by ianco** [comment]
This should be fixed in `0.7.4`

See: https://github.com/hyperledger/aries-cloudagent-python/pull/1721

**Comment by yunxi-zhang** [comment]
@ianco , is the fix available in the `0.7.4-rcx` or formal `0.7.4` to be released?

**Comment by ianco** [comment]
it's in the `0.7.4-rcx` versions

**Comment by yunxi-zhang** [comment]
@ianco, I've quickly tested this in `0.7.4-rc2`, the issue still remains. Could you reopen this ticket?

**Comment by ianco** [comment]
Hi @yunxi-zhang I'll give it a try, I'm surprised there's a difference between indy-sdk and askar ...

**Comment by swcurran** [comment]
Confirmed that when running in Askar mode, there is two entries for each schema.  Steps to replicate:

- Start von-network and Faber
- Wait until invite to copy prompt
- Run API call: http://localhost:8021/api/doc#/schema/get_schemas_created
  - Under indy -- the schema that is created is listed once, under askar, it is there twice:

```
{
  "schema_ids": [
    "LM9gLcfVkR9mD7UEV7w4BL:2:degree schema:9.13.70",
    "LM9gLcfVkR9mD7UEV7w4BL:2:degree schema:9.13.70"
  ]
}
```

If I create another schema, it too is listed twice.

**Comment by swcurran** [comment]
FYI -- to run the demo using askar, add the argument: ` --wallet-type askar` to the `./run_demo` command.

**Comment by ianco** [comment]
FYI I tested with:  `POSTGRES=true ./run_demo faber --wallet-type askar`, running a separate postgres database.

The create schema and create cred def check for duplicate creation (if you try to create the same schema or same cred def twice you get an error message, "... already exists", however ...

The `/schemas/created` shows 2 records for each schema
... and the `/cred-defs/created` also shows 2 records for each cred def

Either the wallet record is getting created twice, or the query is pulling duplicate records (maybe duplicate tags are getting created?)

**Comment by swcurran** [comment]
@andrewwhitehead -- please take a look ASAP.  Thanks!
